#! /bin/bash

srcExt=$1
destExt=$2
srcDir=$3
destDir=$4
opts=$5

for filename in "$srcDir"/*.$srcExt; do
basePath=${filename%.*} #without the file extension
baseName=${basePath##*/}
grep -q "$basePath" converted
if [ $? != 0 ];
then
ffmpeg -i "$filename" $opts -f mp3 "$destDir"/"$baseName"
echo $basePath >> converted
fi
#echo "Conversion from ${srcExt} to ${destExt} for ${baseName} complete!"
done

